
server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/books-management-db?createDatabaseIfNotExist=true
    username: root
    password: pool
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
  application:
    name: BOOKS-SERVICE
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true